### ISSUE TITLE
Secret chats (also ask before accepting them)

### ISSUE THREAD

**Issue by ars3niy** [ars3niy/tdlib-purple#11]
Also check out https://github.com/majn/telegram-purple/issues/249

**Comment by ars3niy** [comment]
createNewSecretChat closeSecretChat updateSecretChat

**Comment by The-Compiler** [comment]
Right now - at least with Bitlbee - I'm getting asked whether I want to accept a secret chat which then gets rejected automatically:

```
21:04 <@root> telegram-tdlib - New request: Request: Secret chat
21:04 <@root> 
21:04 <@root> Accept secret chat with '<name>' on this device?
21:07 <@The-Compiler> yes
21:07 <@root> telegram-tdlib - Accepted: Request: Secret chat
21:07 <@root> purple - Secret chat - Rejected secret chat with '<name>' - Secret chats not supported
```

Is there a way for telegram-tdlib to not prompt at all as long as secret chats aren't supported anyways?

**Comment by ars3niy** [comment]
> Is there a way for telegram-tdlib to not prompt at all as long as secret chats aren't supported anyways?

Or just implement them already.
