### ISSUE TITLE
Build from aur failed

### ISSUE THREAD

**Issue by frostmorn** [ars3niy/tdlib-purple#111]
```-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:10 (message):
  tdlib version 1.6.5 or older is required
```

**Comment by ars3niy** [comment]
There is no good way to solve this. Supporting tdlib 1.6.6 and above would mean failing to build with 1.6.5 and below.

**Comment by frostmorn** [comment]
We could use preprocess directives to make it work with alternative tdlib version

**Comment by BenWiederhake** [comment]
In case you wanna get started with porting to 1.7.0, you may find it helpful to start here: https://github.com/ars3niy/tdlib-purple/pull/98

It compiles, it "works", but it doesn't work correctly.

**Comment by bonfus** [comment]
I compiled you branch on archlinux and I've been using it with pidgin and tdlib 1.7.0 for at least 2 months. I had to remove VOIP. Only glitch is that I cannot make chats persistent.

**Comment by frostmorn** [comment]
yep, I also removed VOIP, and looks like it's okay, but in big chat groups no data about users.
And yep, chats not always visible.

**Comment by BenWiederhake** [comment]
That's why I marked my branch as a draft – the chat names are broken, and I don't consider the code useful yet.

**Comment by ars3niy** [comment]
Now tdlib 1.7.8 or above is required. However, version requirement will likely continue being fairly strict, support for multiple versions takes significant effort to maintain.
