### ISSUE TITLE
Authentication code never sent

### ISSUE THREAD

**Issue by colourful-land** [ars3niy/tdlib-purple#113]
Step:

0. Install [libpurple-telegram-tdlib_0.7.8-1_amd64.deb](https://download.opensuse.org/repositories/home:/ars3n1y/Debian_10/amd64/). Using KDE Neon (Ubuntu 20.04)
1. Add Telegram account from Pidgin by using mobile number (with international prefix)
2. get message: "Enter authentication code": Code sent via: Telegram message (length: 5); Next code will be: SMS: (length: 0)"
3. Not seeing code in Telegram (on Android phone)

Thanks for taking a look

**Comment by colourful-land** [comment]
Any hint?

**Comment by ars3niy** [comment]
Sorry for procrastination. I'm really not sure what to make of it though. If you want to investigate, you can try this:

- quit pidgin
- rename your ~/.purple/tdlib into something (assuming ~/.purple is where pidgin stores everything)
- run `pidgin -d 2>tdlib.log`, it will be as if you're using the plugin for the first time again
- after reproducing the issue, quit pidgin again
- remove the new ~/.purple/tdlib and bring back the original one
- from there you can continue using your pidgin account as if nothing happened
- show tdlib.log in https://github.com/tdlib/td/ and see if they can help

**Comment by ars3niy** [comment]
good thing is, if you don't get any further than requesting authorization code then the log won't contain any personal information other than your phone number

**Comment by colourful-land** [comment]
On a 2nd try it worked but I think the problem is the verification code was sent to a computer that runs Telegram and wasn't found on the mobile. I'll close this issue and replace it with another: https://github.com/ars3niy/tdlib-purple/issues/114 since this one can't be reliably reproduced.
