### ISSUE TITLE
error: ‘numeric_limits’ is not a member of ‘std’

### ISSUE THREAD

**Issue by dchmelik** [ars3niy/tdlib-purple#123]
`[ 14%] Building CXX object rlottie/CMakeFiles/rlottie.dir/src/vector/vrle.cpp.o
/home/user/math/src/network/chat/bitlbee/plugins/tdlib-purple/rlottie/src/vector/vrle.cpp: In member function ‘void VRle::VRleData::updateBbox() const’:
/home/user/math/src/network/chat/bitlbee/plugins/tdlib-purple/rlottie/src/vector/vrle.cpp:128:32: error: ‘numeric_limits’ is not a member of ‘std’
  128 |     int               l = std::numeric_limits<int>::max();
      |                                ^~~~~~~~~~~~~~
/home/user/math/src/network/chat/bitlbee/plugins//tdlib-purple/rlottie/src/vector/vrle.cpp:128:47: error: expected primary-expression before ‘int’
  128 |     int               l = std::numeric_limits<int>::max();
      |                                               ^~~
make[2]: *** [rlottie/CMakeFiles/rlottie.dir/build.make:258: rlottie/CMakeFiles/rlottie.dir/src/vector/vrle.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:623: rlottie/CMakeFiles/rlottie.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
`

This was reported before but wasn't clear how to fix it, before the person quit and closed the issue.

**Comment by smoskovko** [comment]
Just add  "#include <limits>" to vrle.h

More about this issue here: https://www.gnu.org/software/gcc/gcc-11/porting_to.html#header-dep-changes

**Comment by smikrok** [comment]
> Just add "#include " to vrle.h
> 
> More about this issue here: https://www.gnu.org/software/gcc/gcc-11/porting_to.html#header-dep-changes

Add "#include <limits>" to vrle.h

**Comment by ars3niy** [comment]
I've merged the pull request so it should be fixed now. This build job looks like it used gcc 11: https://build.opensuse.org/public/build/home:ars3n1y/xUbuntu_21.10/x86_64/tdlib-purple/_log
