### ISSUE TITLE
Authentication code request unhandled with Spectrum2

### ISSUE THREAD

**Issue by v2e** [ars3niy/tdlib-purple#130]
Hello!
I tried to use the Spectrum2 with tdlib-purple today, and I cannot authorize to Telegram network. Here is the message I can see in the Spectrum2 backend log:

```
555: 2021-12-07 21:17:07,562 INFO  libpurple: telegram-tdlib:Incoming update: authorization state
555: 2021-12-07 21:17:07,562 INFO  libpurple: telegram-tdlib:Authorization state update: authentication code requested
555: 2021-12-07 21:17:07,563 WARN  backend: Unhandled request input. primary=Enter authentication code
Code sent via: Telegram message (length: 5)
Next code will be: SMS (length: 0)

555: 2021-12-07 21:17:07,563 INFO  libpurple: telegram-tdlib:Authentication success on query 4
```
After that my Telegram transport appears in my Jabber client, but it is always gray, and it does not load my contact list at all.

**Comment by ars3niy** [comment]
You need to use at least version 2.0.13 of Spectrum (this is "normal" in earlier versions).

**Comment by v2e** [comment]
I upgraded Spectrum to version 2.0.13, and now it works. Thanks!
