### ISSUE TITLE
Cannot sign up  any more width pidgin

### ISSUE THREAD

**Issue by veto64** [ars3niy/tdlib-purple#132]
message: 
+66832162888
Please enter only numbers in the international phone number format, a leading + following by the country prefix and the phone number.
Do not use any other special chars.

**Comment by ars3niy** [comment]
Looks like this is what you are seeing, which is from the wrong plugin: https://github.com/majn/telegram-purple/blob/master/tgp-request.c#L299

**Comment by ars3niy** [comment]
Protocol "Telegram" in pidgin's Add Account window is telegram-purple, this plugin is "Telegram (tdlib)"

**Comment by veto64** [comment]
Thanks a lot, now it works

https://myridia.com/dev_posts/view/3019
