### ISSUE TITLE
Feature request: Read API Keys from config file

### ISSUE THREAD

**Issue by c0dev0id** [ars3niy/tdlib-purple#140]
Hello,

Passing API keys at compile time works for people that actually compile the code. I would like to package tdlib-purple for OpenBSD. I can create an application and add my keys to the package, but in the nature of Open Source, the API key would be visible and can be used for evil. It's also prohibit by the telegram TOS to give it to third parties.

Therefore I'd like to request a way to pass API_ID and API_HASH at runtime. I think a simple config file in the user home directory would work. This would also free you from the burden to man up and provide you own keys :-)

**Comment by zer0def** [comment]
Wouldn't #129 address this, so that you could specify these on purple account creation?

**Comment by c0dev0id** [comment]
That's even better.
