### ISSUE TITLE
Download voice notes from Spectrum

### ISSUE THREAD

**Issue by vitalyster** [ars3niy/tdlib-purple#148]
I [removed](https://github.com/SpectrumIM/spectrum2/commit/8fcc174ee3a5a59942ae76bf4084ca6b86060822) all outdated Xfer API code from Spectrum, and now it works with most of plugins including tdlib-purple. The only issue is voice notes: tdlib-purple always send voice messages as `voiceNote.tga` file. If I accept them on Spectrum side with `purple_xfer_request_accepted(xfer, "/path/to/voiceNote.tga"`) it downloaded correctly, but if I change basename to something like `voiceNote-1.tga` to keep all previous notes, tdlib-purple started to throw "Error 400: download failed" or something like this and then cancel the download. What can be wrong on my side or is this tdlib-purple issue? Other plugins send voice messages as `{guid}.oga` and everything works as expected

**Comment by ars3niy** [comment]
Seems strange, I don't quite understand how the destination file name can affect anything. Do you think you can show full debug output, which is standard libpurple log at debug level plus stderr output from the PRPL after purple_debug_set_enabled(true)? I'd have to reproduce it myself otherwise.

**Comment by vitalyster** [comment]
After studying the log I found the problem on my side, nevermind
