### ISSUE TITLE
Check if read receipts could be sent other than immediately upon receiving the message

### ISSUE THREAD

**Issue by ars3niy** [ars3niy/tdlib-purple#22]

**Comment by BenWiederhake** [comment]
This is one of the "highly optional" features, since (as far as I know) libpurple does not provide any interface to tell your prpl when the user *actually* reads something.

**Comment by ars3niy** [comment]
So we did check it and the answer is no :)

**Comment by BenWiederhake** [comment]
Well, just because I don't know of a way it doesn't mean there definitely aren't any :P

**Comment by ars3niy** [comment]
purple_conversation_has_focus

**Comment by ars3niy** [comment]
Also check out https://github.com/EionRobb/purple-hangouts/blob/efa7a53e2db4087a1590850423aa16b380bfbbd5/libhangouts.c#L407

**Comment by Dinth** [comment]
Otherwise I love this plugin, but unfortunately, this is a showstopper for me. Having pidgin with tdlib-purple is not only instantly marking all messages sent to me as read, but also by doing that, it prevents notifications on all my other devices, so i dont know if and when someone texts me anymore.

**Comment by ars3niy** [comment]
Made version 0.7.5 which, when used with pidgin, is supposed to mark messages as viewed only when conversation window has focus, and then only for conversation tab that has focus. With used with bitlbee or spectrum, there is account option "read-receipts" to disable marking any messages as viewed.

Let me know if something is still wrong.

**Comment by alaraun** [comment]
Also love the plugin a lot. Would like to have mark as read when actually accessing the the conversation under bitlbee otherwise it is quite unusable when I let it running under screen session.

**Comment by ars3niy** [comment]
I assume that's not possible because bitlbee doesn't seem to notify the plugin when you access a conversation? But there exists account option "read-receipts" to disable them completely.

**Comment by ars3niy** [comment]
It's probably done as best I could

**Comment by vitalyster** [comment]
This does NOT work correctly still: 1) the default value is still TRUE, this is wrong, should be FALSE, and the plugin should NEVER mark as read what is not read yet. 2) this forces to disable read-receipts for spectrum and in this case PURPLE_CONV_UPDATE_UNSEEN signals are ignored, so it is not possible to mark as read from spectrum which is able to mark as read when it is actually read.
