### ISSUE TITLE
See what /me does in telegram-purple, and maybe support it

### ISSUE THREAD

**Issue by ars3niy** [ars3niy/tdlib-purple#26]

**Comment by BenWiederhake** [comment]
It's just a slightly different way of writing a message. It dates back to IRC and maybe even older, and is implemented in basically every chatting platform, even things like Slack or Discord.

Here I wrote `/me waves`, with a bit of normal text around it for comparison:

![Bildschirmfoto_2020-05-12_18-55-43](https://user-images.githubusercontent.com/2690845/81722856-4b683000-9482-11ea-8ff0-cfba053fbaec.png)

**Comment by ars3niy** [comment]
Yeah I know what it does in IRC, just need to look how does it manage do it with libpurple, and whether by any chance it could be a stand-alone protocol-independent plugin instead.

**Comment by BenWiederhake** [comment]
Ah, right, that makes a lot of sense.

**Comment by ars3niy** [comment]
It's a pidgin thing, the message is still transmitted as typed, but is displayed differently when received (unless I'm missing something, but don't think I am).

**Comment by BenWiederhake** [comment]
Huh, you're right, I never noticed that before. o.O

**Comment by ars3niy** [comment]
Solving issues by doing nothing is the best way
