### ISSUE TITLE
Have an AppStream file

### ISSUE THREAD

**Issue by BenWiederhake** [ars3niy/tdlib-purple#31]
For license reasons, don't copy telegram-purples, because it's licensed weirdly. Have only a glance at it maybe, or just use a template.

This might actually turn out to be important, as some package manager interfaces tend to rely on AppStream, I think? I have no idea, I use aptitude.

**Comment by ars3niy** [comment]
I tried to figure out what to do with those appstream specification files, but the best I could manage so far was this:
```
user@newline:~> appstreamcli status
AppStream Status:
Version: 0.10.0

Distribution metadata:
 /usr/share/app-info
  - Empty.

 /var/lib/app-info
  - Empty.

 /var/cache/app-info
  - Empty.

Metainfo files:
  - Found 73 components.
  - Found 46 components in legacy paths.

Summary:
We have information on 0 software components.
user@newline:~> appstreamcli refresh-index
Command 'refresh-index' is unknown.
user@newline:~>
```
In other words, still no idea how to test it.

**Comment by BenWiederhake** [comment]
```
$ appstreamcli search telegram
Identifier: org.telegram.desktop [desktop-application]
Name: Telegram Desktop
Summary: Telegram Desktop messenger
Package: telegram-desktop
Homepage: https://desktop.telegram.org/
Icon: telegram
---
Identifier: telegramdesktop.desktop [desktop-application]
Name: Telegram Desktop
Summary: Official desktop version of Telegram messaging app
Package: telegram-desktop
Icon: telegram
---
Identifier: telegram-purple [addon]
Name: Telegram
Summary: A plugin that adds support for Telegram
Package: telegram-purple
Homepage: https://github.com/majn/telegram-purple
```

telegram-purple drops it's file at either `/usr/local/share/appdata/telegram-purple.metainfo.xml` or`/usr/share/appdata/telegram-purple.metainfo.xml`, depending on the kind of installation.

**Comment by ars3niy** [comment]
I even put `telegram-purple.metainfo.xml` into `/usr/share/appdata`, now it says `Found 74 components` up from 73, yet it still doesn't recognize any "software components", and all the searches show nothing. So I guess the appstream tools I have installed are simply broken.

**Comment by BenWiederhake** [comment]
```
$ appstreamcli status
AppStream Status:
Version: 0.12.10
…
Summary:
We have information on 2588 software components.
``
That might be the case :D

**Comment by ars3niy** [comment]
Added one now
```
$ appstreamcli search telegram
Identifier: tdlib_purple [addon]
Name: Telegram plugin
Summary: Telegram protocol plugin for libpurple using tdlib
Homepage: https://github.com/ars3niy/tdlib-purple
```

**Comment by BenWiederhake** [comment]
There already is one and it gets installed by default, so I guess this can be closed? :)
