### ISSUE TITLE
Easier win32 cmake build

### ISSUE THREAD

**Issue by EionRobb** [ars3niy/tdlib-purple#36]
From PR #34
> Do you have any recommendations for how to go about altering the cmakelists for manually specifying libpurple and glib dirs, so that I don't have to hack up the generated Makefile, before I tackle that as a PR?

Currently the steps are:
```
CXX=c:/cygwin/home/Eion/win32-dev/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/g++ CC=c:/cygwin/home/Eion/win32-dev/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/gcc  /cygdrive/c/Program\ Files/CMake/bin/cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=c:/cygwin/home/Eion/win32-dev/openssl-openssl-3.0.0-alpha1/ -DZLIB_LIBRARY=c:/cygwin/home/Eion/win32-dev/glib-2.38.2/bin/zlib1.dll -DZLIB_INCLUDE_DIR=c:/cygwin/home/Eion/win32-dev/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/i686-w64-mingw32/include -DTd_DIR=c:/cygwin/home/Eion/win32-dev/tdlib/lib/cmake/Td  -DPurple_INCLUDE_DIRS="c:/cygwin/home/Eion/pidgin-2.11.0/libpurple c:/cygwin/home/Eion/win32-dev/glib-2.28.8/include c:/cygwin/home/Eion/win32-dev/glib-2.28.8/include/glib-2.0 c:/cygwin/home/Eion/win32-dev/glib-2.28.8/lib/glib-2.0/include" -DPurple_LIBRARIES=c:/cygwin/home/Eion/pidgin-2.11.0/libpurple/libpurple.dll -G"Unix Makefiles" ..
```
Then edit linklibs.rsp to add in `libglib-2.0-0.dll libgthread-2.0-0.dll -lws2_32 -static-libstdc++ -static-libgcc` and modify linklibs.rsp so that `libcrypto-3.dll libssl-3.dll` becomes `libcrypto.a libssl.a`
Then edit includes_CXX.rsp to fix up the `-I`'s for glib, and move the `-isystem` to after the `tdlib/include`

**Comment by ars3niy** [comment]
But then do you still get errors because FindPkgConfig fails?

**Comment by ars3niy** [comment]
Basically you did everything right, only if you need, you can change CMakeLists.txt something like
```
if (NOT DEFINED NoPkgConfig)
    include(FindPkgConfig)
    pkg_check_modules(Purple REQUIRED purple)
    pkg_get_variable(PURPLE_PLUGIN_DIR purple plugindir)
    pkg_get_variable(PURPLE_DATA_DIR purple datarootdir)
endif (NOT DEFINED NoPkgConfig)
```

and run with `-DNoPkgConfig`

**Comment by ars3niy** [comment]
So you should run cmake with like `-DPurple_INCLUDE_DIRS="/path/to/libpurple;/path/to/glib" -DPurple_INCLUDE_DIRS="/path/to/libpurple/includes;/path/to/glib/includes"`

**Comment by ars3niy** [comment]
For openssl, I just removed shared libraries after building it, and then static libraries were used :-)

**Comment by EionRobb** [comment]
Ah, semicolon for the includes, that makes sense.  I took your idea with removing the shared binaries, by instead linking libcrypto.dll.a to libcrypto.a, rather than deleting the libcrypto-3.dll.

I had to comment out the pkgconfig stuff from CMakeFiles.txt but with
```
CXX=c:/cygwin/home/Eion/win32-dev/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/g++ CC=c:/cygwin/home/Eion/win32-dev/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/gcc  /cygdrive/c/Program\ Files/CMake/bin/cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=c:/cygwin/home/Eion/win32-dev/openssl-openssl-3.0.0-alpha1/ -DZLIB_LIBRARY=c:/cygwin/home/Eion/win32-dev/glib-2.38.2/bin/zlib1.dll -DZLIB_INCLUDE_DIR=c:/cygwin/home/Eion/win32-dev/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/i686-w64-mingw32/include -DTd_DIR=c:/cygwin/home/Eion/win32-dev/tdlib/lib/cmake/Td -DCMAKE_CXX_STANDARD_LIBRARIES="-static-libstdc++ -static-libgcc -lws2_32  -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic" -DPurple_INCLUDE_DIRS="c:/cygwin/home/Eion/pidgin-2.11.0/libpurple;c:/cygwin/home/Eion/win32-dev/glib-2.28.8/include;c:/cygwin/home/Eion/win32-dev/glib-2.28.8/include/glib-2.0;c:/cygwin/home/Eion/win32-dev/glib-2.28.8/lib/glib-2.0/include" -DPurple_LIBRARIES="c:/cygwin/home/Eion/pidgin-2.11.0/libpurple/libpurple.dll;c:/cygwin/home/Eion/win32-dev/glib-2.38.2/bin/libglib-2.0-0.dll;c:/cygwin/home/Eion/win32-dev/glib-2.38.2/bin/libgthread-2.0-0.dll" -DPURPLE_PLUGIN_DIR="C:/Program\ Files\ \(x86\)/Pidgin/plugins" -DPURPLE_DATA_DIR="C:/Program\ Files\ \(x86\)/Pidgin/pixmaps/pidgin/protocols" -G"Unix Makefiles" ..
```
I can get a build with all deps statically compiled in (to a 36MB dll).  Unfortunately the `make install` doesn't work, it tries to install the dll to a "TdExample" folder:
```
$ make install
[ 25%] Built target fmt
[100%] Built target telegram-tdlib
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:36 (file):
  file cannot create directory: C:/Program Files (x86)/TdExample/lib.  Maybe
  need administrative privileges.


make: *** [Makefile:94: install] Error 1
```

**Comment by ars3niy** [comment]
I don't really know why is it trying to install into `C:/Program Files (x86)/TdExample/` of all places, but it's not important. The installation path normally comes from these statements in CMakeLists.txt:
```
install(TARGETS telegram-tdlib LIBRARY DESTINATION "${PURPLE_PLUGIN_DIR}")
install(FILES icons/telegram16.png DESTINATION "${PURPLE_DATA_DIR}/pixmaps/pidgin/protocols/16" RENAME telegram.png)
install(FILES icons/telegram22.png DESTINATION "${PURPLE_DATA_DIR}/pixmaps/pidgin/protocols/22" RENAME telegram.png)
install(FILES icons/telegram48.png DESTINATION "${PURPLE_DATA_DIR}/pixmaps/pidgin/protocols/48" RENAME telegram.png)
```
Without pkgcofig, these variables aren't set either. So you can also set PURPLE_PLUGIN_DIR and PURPLE_DATA_DIR when you run cmake, and then the plugin .dll and icons will be installed accordingly.

**Comment by EionRobb** [comment]
It's a challenge to see since it's all ending up on one line in github, but I am setting those flags:
```
-DPURPLE_PLUGIN_DIR="C:/Program\ Files\ \(x86\)/Pidgin/plugins" 
-DPURPLE_DATA_DIR="C:/Program\ Files\ \(x86\)/Pidgin/pixmaps/pidgin/protocols"
```

**Comment by EionRobb** [comment]
Attached the cmake_install.cmake which starts off with
```
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/TdExample")
endif()
```
[cmake_install.zip](https://github.com/ars3niy/tdlib-purple/files/4627800/cmake_install.zip)

**Comment by EionRobb** [comment]
```
-DCMAKE_INSTALL_PREFIX=""
-DPURPLE_PLUGIN_DIR="C:/PROGRA~2/Pidgin/plugins"
-DPURPLE_DATA_DIR="C:/PROGRA~2/Pidgin/pixmaps/pidgin/protocols"
```
gets it closer, but only installs the icons:
```
$ make install
[ 25%] Built target fmt
[100%] Built target telegram-tdlib
Install the project...
-- Install configuration: "Release"
-- Up-to-date: /lib/libtelegram-tdlib.dll.a
-- Up-to-date: /bin/libtelegram-tdlib.dll
-- Installing: C:/PROGRA~2/Pidgin/pixmaps/pidgin/protocols/pixmaps/pidgin/protocols/16/telegram.png
-- Installing: C:/PROGRA~2/Pidgin/pixmaps/pidgin/protocols/pixmaps/pidgin/protocols/22/telegram.png
-- Installing: C:/PROGRA~2/Pidgin/pixmaps/pidgin/protocols/pixmaps/pidgin/protocols/48/telegram.png
```

**Comment by ars3niy** [comment]
It seems to just ignore PURPLE_PLUGIN_DIR you set, but not PURPLE_DATA_DIR :-/

**Comment by ars3niy** [comment]
I tried to tweak CMakeLists.txt, did it by any chance help?

**Comment by EionRobb** [comment]
It did :)  Thanks
```
$ make install
[ 23%] Built target fmt
[100%] Built target telegram-tdlib
Install the project...
-- Install configuration: "Release"
-- Installing: C:/PROGRA~2/Pidgin/plugins/libtelegram-tdlib.dll.a
-- Up-to-date: C:/PROGRA~2/Pidgin/plugins/libtelegram-tdlib.dll
-- Up-to-date: C:/PROGRA~2/Pidgin/pixmaps/pidgin/protocols/pixmaps/pidgin/protocols/16/telegram.png
-- Up-to-date: C:/PROGRA~2/Pidgin/pixmaps/pidgin/protocols/pixmaps/pidgin/protocols/22/telegram.png
-- Up-to-date: C:/PROGRA~2/Pidgin/pixmaps/pidgin/protocols/pixmaps/pidgin/protocols/48/telegram.png
```

**Comment by EionRobb** [comment]
Just need `if (NOT DEFINED NoPkgConfig)` and then it's perfect :)

**Comment by ars3niy** [comment]
Done, run cmake with `-DNoPkgConfig=True`

**Comment by EionRobb** [comment]
Works great.  Thanks!  In case anyone else is wanting to build this on windows in the future, my cmake config is:
`
CXX=c:/cygwin/home/Eion/win32-dev/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/g++ CC=c:/cygwin/home/Eion/win32-dev/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/bin/gcc  /cygdrive/c/Program\ Files/CMake/bin/cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=c:/cygwin/home/Eion/win32-dev/openssl-openssl-3.0.0-alpha1/ -DZLIB_LIBRARY=c:/cygwin/home/Eion/win32-dev/glib-2.38.2/bin/zlib1.dll -DZLIB_INCLUDE_DIR=c:/cygwin/home/Eion/win32-dev/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/i686-w64-mingw32/include -DTd_DIR=c:/cygwin/home/Eion/win32-dev/tdlib/lib/cmake/Td -DCMAKE_CXX_STANDARD_LIBRARIES="-static-libstdc++ -static-libgcc -lws2_32  -Wl,-Bstatic -lstdc++ -lpthread -Wl,-Bdynamic" -DPurple_INCLUDE_DIRS="c:/cygwin/home/Eion/pidgin-2.11.0/libpurple;c:/cygwin/home/Eion/win32-dev/glib-2.28.8/include;c:/cygwin/home/Eion/win32-dev/glib-2.28.8/include/glib-2.0;c:/cygwin/home/Eion/win32-dev/glib-2.28.8/lib/glib-2.0/include" -DPurple_LIBRARIES="c:/cygwin/home/Eion/pidgin-2.11.0/libpurple/libpurple.dll;c:/cygwin/home/Eion/win32-dev/glib-2.38.2/bin/libglib-2.0-0.dll;c:/cygwin/home/Eion/win32-dev/glib-2.38.2/bin/libgthread-2.0-0.dll" -DCMAKE_INSTALL_PREFIX="" -DPURPLE_PLUGIN_DIR="C:/PROGRA~2/Pidgin/plugins" -DPURPLE_DATA_DIR="C:/PROGRA~2/Pidgin/pixmaps/pidgin/protocols" -DNoPkgConfig=True -G"Unix Makefiles" ..
`
