### ISSUE TITLE
Writing code for this project is messing up my elbow

### ISSUE THREAD

**Issue by ars3niy** [ars3niy/tdlib-purple#37]
Intermittent regression has been observed, suspected to be caused by recent commits

**Comment by BenWiederhake** [comment]
Take your time, don't hurt yourself :)

**Comment by BenWiederhake** [comment]
I've found that putting a folded towel in front of the keyboard helps supporting my arms. Yet another good use for towels (I hope Douglas Adams would be proud of me).
