### ISSUE TITLE
Respect account proxy settings

### ISSUE THREAD

**Issue by EionRobb** [ars3niy/tdlib-purple#38]
The proxy settings in use for the account aren't being used, so the plugin won't connect via TOR settings specified in Pidgin/libpurple/account settings

**Comment by ars3niy** [comment]
Added in a recent commit. Note that tdlib only supports HTTP and SOCKS5 proxy servers, so if SOCKS4 or TOR proxy is configured, it cannot be used. Of course, the official desktop client does not support those proxy types either.

Right now unsupported proxy type will result in connection error, but maybe a warning dialog and fallback to direct connection would be a better option, I'm not sure.

**Comment by EionRobb** [comment]
Almost! 

The proxy functions should really do it for you, but if they come back to say "global" then you should be referring to the global proxy settings 

Tor is implemented in pidgin as a socks5 proxy endpoint, but configured so that dns look ups go through the proxy instead of outside it. Not sure if "use proxy for dns" is a config option in tdlib though

**Comment by ars3niy** [comment]
> if they come back to say "global" then you should be referring to the global proxy settings

purple_proxy_get_setup appears to handle it all.
> Not sure if "use proxy for dns" is a config option in tdlib though

Looks like it is not. It will either always do it, or never – don't know which one.
