### ISSUE TITLE
Unable to enter login code in bitlbee-purple

### ISSUE THREAD

**Issue by rodneyrod** [ars3niy/tdlib-purple#50]
Tested on Debian Testing

Steps to reproduce:
1. Install bitlbee-libpurple
2. Add OpenSUSE repo and install tdlib-purple package
3. Create account in Bitlbee with mobile number
4. Connect account

After this it will prompt in an existing Telegram app with the login code, but there's nowhere to put this code in Bitlbee. A workaround for this was put in place for telegram-purple, could that be ported to this?

**Comment by ars3niy** [comment]
Strange, I did test it with bitlbee. In fact, I've just tested it on Debian testing (bitlbee-libpurple 3.6-1.1). Here is how it should look like.

![screenshot](https://user-images.githubusercontent.com/3534650/83864586-3a2ede00-a725-11ea-96f9-67263a87e095.png)
![screenshot4](https://user-images.githubusercontent.com/3534650/83864609-431faf80-a725-11ea-9a00-82ca4bf234ac.png)
![screenshot7](https://user-images.githubusercontent.com/3534650/83864652-529ef880-a725-11ea-98e0-693e93f831b4.png)

**Comment by rodneyrod** [comment]
Looks like it might have been a bug with mirc, tried with a more recent build and it's all working now besides an unrelated segfault.
Might test that one again too since it's been a few days and updates have come out since. Happy to close this out.
