### ISSUE TITLE
List supergroup members

### ISSUE THREAD

**Issue by BenWiederhake** [ars3niy/tdlib-purple#55]
Expected behavior: In pidgin, the list of members in a group is visible
Actual behavior: It displays that there are no users in the room.

Other than that, I'm finally using it, too. Thank you again, and I hope I can soon start really contributing instead of just complaining ^^'

**Comment by ars3niy** [comment]
It currently works for basic groups, such as the telegram-purple group, but not for supergroups.

**Comment by ars3niy** [comment]
Added in new version
