### ISSUE TITLE
Enhancement: Trim usernames that don't have a surname

### ISSUE THREAD

**Issue by BenWiederhake** [ars3niy/tdlib-purple#66]
For example, my surname is not set on Telegram. Hence, my username is displayed as `Ben `, notice the trailing space.

It's not too much of a problem, the extra whitespace only looks a bit silly.

**Comment by ars3niy** [comment]
Fixed in https://github.com/ars3niy/tdlib-purple/commit/e4f4eef6cd2e1c639cd921f58b03e41aa5ec498a
