### ISSUE TITLE
Build fails around MessagesManager.cpp.o] Error 1

### ISSUE THREAD

**Issue by Strykar** [ars3niy/tdlib-purple#71]
Build fails on Arch Linux (aur pkg) with:
```
[ 52%] Building CXX object CMakeFiles/tdcore.dir/td/telegram/MessagesDb.cpp.o
[ 52%] Building CXX object CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/tdcore.dir/build.make:1096: CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o] Error 1
make[2]: *** Deleting file 'CMakeFiles/tdcore.dir/td/telegram/MessagesManager.cpp.o'
make[1]: *** [CMakeFiles/Makefile2:468: CMakeFiles/tdcore.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```
Where do I start to troubleshoot this?

**Comment by The-Compiler** [comment]
Looks like your C++ compiler was killed, most likely because you're running out of RAM. `dmesg` might say more if that's the case. You might want to reduce the number of jobs (`-j`), close some other application eating your RAM, or perhaps [download more RAM](https://downloadram.net/) :wink:

**Comment by ars3niy** [comment]
You can double-check it in the kernel log, but I'm pretty sure it's OOM killer. tdlib is notorious for requiring more than a gigabyte of RAM to compile some files.

I think it has a PHP script to split the worst offenders into multiple files, haven't tried it myself though.

**Comment by Strykar** [comment]
That was it, thank you. Happily ate up 10 GB of RAM when compiled on my desktop, closing. Working well in Bitlbee for single user chats. Cheers @ars3niy @The-Compiler
