### ISSUE TITLE
HTML not properly stripped

### ISSUE THREAD

**Issue by BenWiederhake** [ars3niy/tdlib-purple#72]
Steps to reproduce:
1. Open this PDF in your *browser*, it actually must be your browser: https://ftp.cs.wisc.edu/paradyn/technical_papers/fuzz2020.pdf
2. Copy some text out of it that goes across at least one linebreak
3. Paste it in pidgin
4. Send it

Expected, option 1:
In Step 3, the text appears in the edit box, without mangling
In Step 4, the text **as it was shown in the edit box** gets sent

Expected, option 2:
In Step 3, the text plus some HTML tag `<font size="3">` appears in the edit box
In Step 4, the text **as it was shown in the edit box** gets sent (Including any changes if you did them)

Actual:
In Step 3, the text appears in the edit box, without mangling
In Step 4, a different text gets sent to the group chat, and suddenly contains some HTML tag `<font size="3">`, in **contrast to what was shown in the edit box**

Have some screenshots for reference:

Pidgin, edit box after Step 3:

![html-pidgin-editbox](https://user-images.githubusercontent.com/2690845/90511819-5e635e00-e15d-11ea-824e-79568a0d37c6.png)

Pidgin, chat window after Step 4:

![html-pidgin-chat](https://user-images.githubusercontent.com/2690845/90511810-5c010400-e15d-11ea-8c60-00aaf67dcf20.png)

Telegram web chat (to demonstrate that it's not just a display error in Pidgin):

![chat-webtelegram](https://user-images.githubusercontent.com/2690845/90511808-5acfd700-e15d-11ea-9b00-71bb4d70cf01.png)

**Comment by ars3niy** [comment]
Fixed in git. Hebrew and Arabic still look fine.

**Comment by ars3niy** [comment]
Made a new version with the fix
