### ISSUE TITLE
Translations on Windows: How to distribute?

### ISSUE THREAD

**Issue by BenWiederhake** [ars3niy/tdlib-purple#78]
Currently, Windows users only get a `.dll` file, attached to the release. Thus, there are no translations.

Those translations should somehow also be available to Windows users. Currently, their only option is downloading the repo, getting gettext to work and manually invoking it (or, even worse, figure out the incantation that builds *only* the `.mo` files), and then dropping them in a magic location that is documented nowhere.

1. We could have an installer like telegram-purple had. If we choose nsis, we can reuse most of the [telegram-purple nsis template](https://github.com/majn/telegram-purple/blob/master/telegram-purple.nsi.awk-in).
2. Alternatively, we could attach all the generated `po/*.mo` files to the releases, somehow, and also document where it's supposed to go. Keep in mind that their final destination will be something like `C:/Programs (x86)/Pidgin/locale/pt_BR/LC_MESSAGES/tdlib-purple.mo`, in other words: All files should be named `tdlib-purple.mo`. This might complicate things.

Thanks to Siggi0904 who pointed out this issue.

**Comment by ars3niy** [comment]
I've made an nsis script – so far, without translations.

**Comment by ars3niy** [comment]
Actually, added translations to the installer as well.

**Comment by BenWiederhake** [comment]
I like the `!include` approach, it's a little bit less mystic than 變 :D
