### ISSUE TITLE
[DATA LOSS] tdlib-purple removes files

### ISSUE THREAD

**Issue by ildar** [ars3niy/tdlib-purple#85]
In `~/.config/purple/tdlib/<myphoneno>/` I have some folders replaced by symlinks:
> documents → /some/storage/folder
> thumbnails → /tmp/cache/
> music → /some/storage/folder
> photos → /some/storage/folder
> stickers → /some/storage/folder/stickers
> temp → /some/storage/folder/temp

Suddenly I got /some/storage/folder **emptied** (DATA LOSS!)
And `documents` recreated (as folder).

Please don't do that. Please fix ASAP.

**Comment by ars3niy** [comment]
Sorry for the data loss, however this is related to tdlib itself and how it treats its temporary files, it's nothing I can change. Please report at https://github.com/tdlib/td .

It might be better not to point those symlinks to directories containing non-tdlib-related files, though.

**Comment by ars3niy** [comment]
Essentially, you end up storing important files in tdlib's temporary storage directory. All I can do is advise not to do this.

**Comment by ildar** [comment]
Can you please confirm that `~/.config/purple/tdlib/<myphoneno>/documents`
is treated as temporary?
I can agree with `~/.config/purple/tdlib/<myphoneno>/temp` but not documents
!
BTW IIRC previous version of tdlib-purple seemed to miss that `temp`
directory.
Anyway, thanks, I'll go file the issue at tdlib.

**Comment by ildar** [comment]
На всякий случай: @ars3niy, can you not control this part from tdlib-purple?

**Comment by ildar** [comment]
https://github.com/tdlib/td/issues/1250

**Comment by ildar** [comment]
Looks like this influenced the behavior:
https://github.com/ars3niy/tdlib-purple/blob/260aca2dcc78cf3626822fa0bd34f00611eea084/td-client.cpp#L398
Let's see what TDLib guys propose (or fix).

**Comment by ildar** [comment]
The discussion bottomline: https://github.com/ars3niy/tdlib-purple/issues/86
