### ISSUE TITLE
change `tdlib` placement

### ISSUE THREAD

**Issue by ildar** [ars3niy/tdlib-purple#86]
per TDlib devs, the whole `tdlib` folder is a cache. Hence it's reasonable to place it in:
1. `~/.cache` for Unix platforms
2. out of .../Roaming/ for Windows.

**Comment by ars3niy** [comment]
It's not only cache though, it's also authentication data (the one that makes SMS authentication code go away after first login). That stuff is akin to saved password and there is an argument to be made that it should be stored inside the same directory saved passwords are in – that is to say, right where it is now.

**Comment by ildar** [comment]
> It's not only cache though, it's also authentication data

I thought so too. But levlam wrote (
https://github.com/tdlib/td/issues/1250#issuecomment-709059930):
> They are "cache files". Some data from the database or the whole
"db.sqlite" file can be deleted any time.

Am I missing something?

**Comment by ars3niy** [comment]
It can be deleted, you'll just receive one more SMS.

**Comment by ildar** [comment]
You mean that holding cache data in ~/.cache (or alike) isn't a good idea
in this case?

**Comment by ars3niy** [comment]
Yes, because it must be in the libpurple user directory (where it currently is) on bitlbee and spectrum, it must be in the same location for pidgin and finch, but in different locations for pidgin and telepathy-haze. The only good way to get this right is to keep it as it is.

**Comment by ildar** [comment]
I see.
I sym-linked the whole `tdlib`, should work hopefully.
Thanks.
