### ISSUE TITLE
[FR] add option for enable_storage_optimizer_

### ISSUE THREAD

**Issue by ildar** [ars3niy/tdlib-purple#87]
This option controls whether downloaded files be autodeleted.
Used here: https://github.com/ars3niy/tdlib-purple/blob/260aca2dcc78cf3626822fa0bd34f00611eea084/td-client.cpp#L398

I think some users want to keep files and some don't. Having this option would make both happy.

**Comment by ars3niy** [comment]
> I think some users want to keep files and some don't

This is demonstrably true, isn't it? You do, I don't, Q.E.D.

I'll add this since it's simple and because why not.

**Comment by ars3niy** [comment]
(I'm not a GNOME developer: the more options, the more mature the product looks)

**Comment by ildar** [comment]
Awesome! 🙂

**Comment by ars3niy** [comment]
Added in rew release
