### ISSUE TITLE
Chats in two tabs, despite already being in my buddy list

### ISSUE THREAD

**Issue by BenWiederhake** [ars3niy/tdlib-purple#89]
I'm using 147b643 (a bit after v0.7.1).

Steps to reproduce (I guess):
- Run tdlib-purple in pidgin
- Make the system go to stand-by
- Chat a bit using other clients
- Resume from stand-by
- Observe two tabs for a single conversation, sometimes, rarely.

I don't really understand why, but I do notice that a specific contact ("J") was affected twice now, another contact ("M") only once, and that I see this only rarely. Most recently, out of seven chats, only two were affected.

I have no clue whether this may be a consequence / latent bug of the reordering-code or not.

**Comment by ars3niy** [comment]
This is https://github.com/ars3niy/tdlib-purple/issues/84
