### ISSUE TITLE
Support file transfers in group chats

### ISSUE THREAD

**Issue by nodiscc** [ars3niy/tdlib-purple#92]
I would like to send a file/image in a group chat, but currently the `Send file...` action in menus is grayed out. Drag-and-dropping files to the chat window does not have any effect.

**Comment by ars3niy** [comment]
It's supported already, but you need libpurple and pidgin ≥2.14 to send files into group chats. Images should be possible even with 2.13.x I think.

**Comment by ars3niy** [comment]
Accordingly, the plugin has to be built against libpurple ≥2.14, so most of my packages from build.opensuse.org can't do this.

**Comment by fulalas** [comment]
I've just built everything from scratch using libpurple 2.14.1 and the only way to send images in group chats is by clicking on insert -> image. So no drag and drop like we have for individual users, and no way to send images in their original format.

**Comment by ars3niy** [comment]
That you cannot drag and drop images from file manager into group chat is a missing feature in Pidgin. It is, however, possible to send files from conversation menu ("Send file..." menu item on the screenshot below).

![send_file_to_chat](https://user-images.githubusercontent.com/3534650/98573589-4f50ff80-22b7-11eb-99d1-66730cde9bdb.png)

**Comment by nodiscc** [comment]
> you need libpurple and pidgin ≥2.14

```
$ apt policy libpurple0 pidgin | grep Installed
  Installed: 2.13.0-2+b1
  Installed: 2.13.0-2+b1
```

It would explain why I don't have this feature. I'll try to build libpurple/pidgin from source (or most likely, wait for Debian 11). Thanks!

**Comment by BenWiederhake** [comment]
Or use Debian Testing, like I (and many other people) do ;)

**Comment by nodiscc** [comment]
/offtopic Debian Testing's security policy doesn't suit me (I'd rather use sid). I use stable (because I like the unchanging nature of it + good security support) + stable-backports with everything pinned to stable except kernels/firmware/drivers (hardware support), and am ready to wait ~1.5 years for features like this :) Creating [backported packages](https://wiki.debian.org/SimpleBackportCreation) is also really easy in most cases (have not tried with pidgin)
