### ISSUE TITLE
Unexpected response to downloading file for stickers

### ISSUE THREAD

**Issue by ildar** [ars3niy/tdlib-purple#96]
> (15:08:46) telegram-tdlib: Unexpected response to downloading file: id -1679978726

**Comment by ars3niy** [comment]
That's a standard error response, perhaps I should improve this log message. For now, you can look at tdlib's log to see what the error message is.

**Comment by ildar** [comment]
> For now, you can look at tdlib's log to see what the error message is.
You mean with `pidgin -d` ? Or I can see it somewhere else without
restarting pidgin?

**Comment by ars3niy** [comment]
That's a late reply if I ever saw one but yes, pidgin -d was the only option. I've committed improved log message, will be included in next release.

**Comment by ildar** [comment]
Thanks!
